default: &default
  adapter: postgresql
  encoding: unicode
  username: elly
  password: immortal
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: jello_server_development

test:
  <<: *default
  database: jello_server_test

production:
  <<: *default
  database: jello_server_production
  username: jello_server
  password: <%= ENV['JELLO_SERVER_DATABASE_PASSWORD'] %>
